# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l2_norm <- function(x) {
    .Call('_bayesianrvfl_l2_norm', PACKAGE = 'bayesianrvfl', x)
}

matern52_kxx_cpp <- function(x, sigma, l) {
    .Call('_bayesianrvfl_matern52_kxx_cpp', PACKAGE = 'bayesianrvfl', x, sigma, l)
}

matern52_kxy_cpp <- function(x, y, sigma, l) {
    .Call('_bayesianrvfl_matern52_kxy_cpp', PACKAGE = 'bayesianrvfl', x, y, sigma, l)
}

cbind_cpp <- function(x, y) {
    .Call('_bayesianrvfl_cbind_cpp', PACKAGE = 'bayesianrvfl', x, y)
}

l2_dist <- function(x, y) {
    .Call('_bayesianrvfl_l2_dist', PACKAGE = 'bayesianrvfl', x, y)
}

l2_distmat <- function(y, x) {
    .Call('_bayesianrvfl_l2_distmat', PACKAGE = 'bayesianrvfl', y, x)
}

one_hot_encode_cpp <- function(x_clusters, n_clusters) {
    .Call('_bayesianrvfl_one_hot_encode_cpp', PACKAGE = 'bayesianrvfl', x_clusters, n_clusters)
}

