# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simpson_integral_cpp <- function(x, y) {
    .Call(`_simulatetimeseries_simpson_integral_cpp`, x, y)
}

